# permissions for end users to view aclbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: consul-acl-operator
    app.kubernetes.io/managed-by: kustomize
  name: aclbinding-viewer-role
rules:
- apiGroups:
  - consul.cloudopskit.org.cloudopskit.org
  resources:
  - aclbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - consul.cloudopskit.org.cloudopskit.org
  resources:
  - aclbindings/status
  verbs:
  - get
