apiVersion: consul.cloudopskit.org.cloudopskit.org/v1alpha1
kind: AclPolicy
metadata:
  labels:
    app.kubernetes.io/name: consul-acl-operator
    app.kubernetes.io/managed-by: kustomize
  name: aclpolicy-sample
spec:
  # TODO(user): Add fields here
