apiVersion: consul.cloudopskit.org.cloudopskit.org/v1alpha1
kind: AclRole
metadata:
  labels:
    app.kubernetes.io/name: consul-acl-operator
    app.kubernetes.io/managed-by: kustomize
  name: aclrole-sample
spec:
  # TODO(user): Add fields here
